htl_immobilier_homepage:
    path:     /
    defaults: { _controller: HTLImmobilierBundle:Default:index }
accueil:
    path:     /front/bien/accueil
    defaults: { _controller: HTLImmobilierBundle:Front:accueil }
search:
    path:     /front/bien/search
    defaults: { _controller: HTLImmobilierBundle:Front:searchBien }
reserver:
    path:     /front/bien/
    defaults: { _controller: HTLImmobilierBundle:Front:reserverBien }
listebien:
    path:     /front/bien/listebien
    defaults: { _controller: HTLImmobilierBundle:Front:listeBien }
searchprix:
    path:     /front/bien/prix
    defaults: { _controller: HTLImmobilierBundle:Front:searchPrix}
searchlocalite:
    path:     /front/bien/localite
    defaults: { _controller: HTLImmobilierBundle:Front:searchLocalite }
listeadmin:
    path:     /front/bien/admin
    defaults: { _controller: HTLImmobilierBundle:Front:listeAdmin }
listereservation:
    path:     /front/bien/reservation
    defaults: { _controller: HTLImmobilierBundle:Front:listeReservation }
details:
    path:     /front/bien/details
    defaults: { _controller: HTLImmobilierBundle:Front:detailsReservation }
contrat:
    path:     /front/bien/contrat
    defaults: { _controller: HTLImmobilierBundle:Front:contratReservation }
listetype:
    path:     /front/bien/typebien
    defaults: { _controller: HTLImmobilierBundle:Front:listTypebien }
listelocalite:
    path:     /front/bien/listelocalite
    defaults: { _controller: HTLImmobilierBundle:Front:listelocalite }
list:
    path:     /listbien
    defaults: { _controller: HTLImmobilierBundle:Admin:listBien }

edit:
    path:     /edit/{id}
    defaults: { _controller: HTLImmobilierBundle:Admin:edit }
    requirements:
        id: \d+

supprimer:
    path:     /supprimer{id}
    defaults: { _controller: HTLImmobilierBundle:Admin:supprimer }
    requirements:
        id: \d+


admin:
    path:     /admin
    defaults: { _controller: HTLImmobilierBundle:Admin:admin }
   