<?php

namespace HTL\ImmobilierBundle\Repository;

/**
 * TypebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypebienRepository extends \Doctrine\ORM\EntityRepository
{
     public function FindAllBientypebien($libelletype)
    {

             return $this->getEntityManager()
                ->createQuery(
                    'SELECT b.id,b.nombien,l.libellelocalite,b.prixlocation,b.description,t.libelletype,i.image FROM HTLImmobilierBundle:Bien b,HTLImmobilierBundle:Localite l,HTLImmobilierBundle:Typebien t,HTLImmobilierBundle:Image i WHERE b.libellelocalite=l.id AND b.typebien=t.id and b.id=i.bien and t.libelletype=:libelletype'
                )
                 ->setParameter('libelletype',  $libelletype)->execute();
             
        }
}
